const $ = (selector) => document.querySelector(selector);
const modal = $('#modal'); const content = $('#modal-content'); const toast = $('#toast');
const showToast = (message) => { toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 3000); };
const api = async (url, options = {}) => { const response = await fetch(url, options); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Something went wrong.'); return data; };
const imageFor = (item) => item?.image || 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=500&q=80';
const outfitVisual = (outfit) => `<div class="outfit-pieces">${['top','bottom','shoes','accessory'].map((key) => outfit[key] ? `<img src="${imageFor(outfit[key])}" alt="${key}">` : '').join('')}</div>`;
function openModal(type) { modal.classList.add('open'); modal.setAttribute('aria-hidden','false'); if (type === 'add') renderAdd(); else if (type === 'profile') renderProfile(); else renderAuth(type); }
function closeModal() { modal.classList.remove('open'); modal.setAttribute('aria-hidden','true'); }
function renderAuth(type = 'login') { const register = type === 'register'; content.innerHTML = `<p class="eyebrow">VESTIQ / ${register ? 'New account' : 'Welcome back'}</p><h2>${register ? 'Create your<br><em>edit.</em>' : 'Return to<br><em>your style.</em>'}</h2><form class="form" id="auth-form">${register ? '<label>Name<input name="name" required minlength="2"></label>' : ''}<label>Email<input name="email" type="email" required></label><label>Password<input name="password" type="password" required minlength="6"></label><button class="button dark" type="submit">${register ? 'Create account' : 'Sign in'} <span>↗</span></button></form><button class="switch" data-auth-switch="${register ? 'login' : 'register'}">${register ? 'Already have an account? Sign in' : 'New here? Create an account'}</button>`; $('#auth-form').onsubmit = async (event) => { event.preventDefault(); const form = new FormData(event.target); try { const data = await api(`/api/auth/${register ? 'register' : 'login'}`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(Object.fromEntries(form)) }); localStorage.setItem('vestiqUser', JSON.stringify(data.user)); closeModal(); showToast(`Welcome, ${data.user.name}.`); } catch (error) { showToast(error.message); } }; }
function renderProfile() { const user = JSON.parse(localStorage.getItem('vestiqUser') || 'null'); content.innerHTML = user ? `<p class="eyebrow">Your account</p><h2>${user.name}</h2><p>${user.email}</p><button class="button dark" id="signout">Sign out <span>↗</span></button>` : `<p class="eyebrow">Your account</p><h2>Make it<br><em>personal.</em></h2><p>Sign in to keep your edit close.</p><button class="button dark" id="profile-login">Sign in <span>↗</span></button>`; $('#signout')?.addEventListener('click', () => { localStorage.removeItem('vestiqUser'); closeModal(); showToast('Signed out.'); }); $('#profile-login')?.addEventListener('click', () => renderAuth()); }
function renderAdd() { content.innerHTML = `<p class="eyebrow">Wardrobe / New piece</p><h2>Add a<br><em>favourite.</em></h2><form class="form" id="add-form"><label>Image<input name="image" type="file" accept="image/*" required></label><img class="preview" id="preview" alt="Selected image preview" hidden><label>Name<input name="name" placeholder="e.g. Relaxed linen shirt" required></label><label>Category<select name="category"><option>Shirt</option><option>T-shirt</option><option>Crop top</option><option>Pants</option><option>Jeans</option><option>Skirt</option><option>Dress</option><option>Jacket</option><option>Shoes</option><option>Accessory</option></select></label><label>Color / details<input name="color" placeholder="e.g. Ink black, cotton"></label><button class="button dark" type="submit">Save piece <span>↗</span></button></form>`; const input = content.querySelector('[name=image]'); input.onchange = () => { const file = input.files[0]; if (file) { const preview = $('#preview'); preview.src = URL.createObjectURL(file); preview.hidden = false; } }; $('#add-form').onsubmit = async (event) => { event.preventDefault(); const button = event.target.querySelector('button'); button.disabled = true; try { await api('/api/wardrobe', { method:'POST', body:new FormData(event.target) }); closeModal(); await loadWardrobe(); showToast('Piece added to your edit.'); } catch (error) { showToast(error.message); button.disabled = false; } }; }
async function loadWardrobe() { const grid = $('#wardrobe-grid'); try { const { items } = await api('/api/wardrobe'); grid.innerHTML = items.length ? items.map((item) => `<article class="wardrobe-card"><button class="delete-item" data-delete="${item.id}" aria-label="Delete ${item.name}">×</button><img src="${imageFor(item)}" alt="${item.name}" onerror="this.src='https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=500&q=80'"><h3>${item.name}</h3><div class="card-meta"><span>${item.category} · ${item.color}</span><span>${new Date(item.dateAdded).toLocaleDateString()}</span></div></article>`).join('') : '<div class="loading">Your wardrobe is waiting for its first story.<br>Use “Add clothing” to begin.</div>'; grid.querySelectorAll('[data-delete]').forEach((button) => button.onclick = async () => { try { await api(`/api/wardrobe/${button.dataset.delete}`, { method:'DELETE' }); await loadWardrobe(); showToast('Piece removed.'); } catch (error) { showToast(error.message); } }); } catch (error) { grid.innerHTML = `<div class="loading">${error.message}</div>`; } }
async function buildPlanner() { const button = $('#planner-btn'); button.disabled = true; button.textContent = 'Composing...'; try { const data = await api('/api/ai/planner', { method:'POST' }); $('#planner-grid').innerHTML = data.days.map(({day,mood,outfit}) => `<article class="day-card"><h3>${day}</h3>${outfitVisual(outfit)}<p>${mood}</p></article>`).join(''); showToast(data.aiConnected ? 'AI edit composed.' : 'Your wardrobe edit is ready.'); } catch (error) { showToast(error.message); } finally { button.disabled = false; button.innerHTML = 'Build my week <span>↗</span>'; } }
async function findMatch() { const button = $('#match-btn'); button.disabled = true; button.textContent = 'Finding...'; try { const { outfit, note } = await api('/api/ai/match', { method:'POST' }); $('#match-result').innerHTML = `<div class="match-result"><p class="eyebrow">Your next look</p><h3>Balanced, with a point of view.</h3>${outfitVisual(outfit)}<p>${note}</p></div>`; showToast('Match found from your wardrobe.'); } catch (error) { showToast(error.message); } finally { button.disabled = false; button.innerHTML = 'Find my match <span>→</span>'; } }
document.addEventListener('click', (event) => { const trigger = event.target.closest('[data-modal]'); if (trigger) openModal(trigger.dataset.modal); const switcher = event.target.closest('[data-auth-switch]'); if (switcher) renderAuth(switcher.dataset.authSwitch); if (event.target === modal || event.target.closest('.modal-close')) closeModal(); });
$('.menu').onclick = () => $('nav').classList.toggle('open'); document.querySelectorAll('nav a').forEach((link) => link.onclick = () => $('nav').classList.remove('open')); $('#planner-btn').onclick = buildPlanner; $('#match-btn').onclick = findMatch; loadWardrobe();